// Lightweight PDF helpers for printing student/class lists & ID cards.
import { jsPDF } from "jspdf";
import type { Student } from "@/lib/eduvest/dashboard-mock";

type School = { name: string; primaryColor?: string };

function hexToRgb(hex: string): [number, number, number] {
  const h = (hex || "#16A34A").replace("#", "");
  const v = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
  const n = parseInt(v, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function header(doc: jsPDF, school: School, title: string, subtitle: string) {
  const [r, g, b] = hexToRgb(school.primaryColor || "#16A34A");
  doc.setFillColor(r, g, b);
  doc.rect(0, 0, 210, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text(school.name || "School", 14, 13);
  doc.setFontSize(10);
  doc.text(title, 210 - 14, 11, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(subtitle, 210 - 14, 17, { align: "right" });
}

export type StudentSortKey = "alphabetical" | "fees" | "registration" | "class";

export function printStudentList(
  students: Student[],
  school: School,
  sort: StudentSortKey,
  scope: string,
) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const titleMap: Record<StudentSortKey, string> = {
    alphabetical: "Student list — alphabetical",
    fees: "Student list — by fees",
    registration: "Student list — by registration",
    class: "Student list — by class",
  };
  header(doc, school, titleMap[sort], `${scope} · ${students.length} students`);

  const sorted = [...students].sort((a, b) => {
    if (sort === "alphabetical") return a.name.localeCompare(b.name);
    if (sort === "fees") return b.totalFees - b.paidFees - (a.totalFees - a.paidFees);
    if (sort === "registration") return a.registration.localeCompare(b.registration);
    return (a.workspace + a.level + a.name).localeCompare(b.workspace + b.level + b.name);
  });

  let y = 32;
  doc.setFontSize(8);
  doc.setTextColor(110, 110, 110);
  doc.setFont("helvetica", "bold");
  doc.text("#", 14, y);
  doc.text("Name", 22, y);
  doc.text("ID", 78, y);
  doc.text("Class", 110, y);
  doc.text("Status", 140, y);
  doc.text("Balance", 196, y, { align: "right" });
  y += 2;
  doc.setDrawColor(220, 220, 220);
  doc.line(14, y, 196, y);
  y += 4;

  doc.setFont("helvetica", "normal");
  doc.setTextColor(20, 20, 20);
  sorted.forEach((s, i) => {
    if (y > 280) {
      doc.addPage();
      y = 20;
    }
    const balance = s.totalFees - s.paidFees;
    doc.text(String(i + 1), 14, y);
    doc.text(s.name.slice(0, 28), 22, y);
    doc.text(s.studentId, 78, y);
    doc.text(`${s.workspace} · ${s.level}`.slice(0, 24), 110, y);
    doc.text(s.registration, 140, y);
    doc.text(balance > 0 ? `XAF ${balance.toLocaleString()}` : "Paid", 196, y, { align: "right" });
    y += 6;
  });

  doc.setFontSize(7);
  doc.setTextColor(140, 140, 140);
  doc.text("Generated by EduVest", 14, 290);
  doc.text(new Date().toLocaleString(), 196, 290, { align: "right" });
  doc.save(`students-${sort}-${Date.now()}.pdf`);
}

// Two-sided digital ID card on a single page.
export type IdCardData = {
  name: string;
  role: "Student" | "Teacher";
  detail: string;
  photo?: string;
  code: string;
  token: string;
  school: School;
  emergencyContact?: string;
  schoolContact?: string;
};

export function buildIdCardPdf(data: IdCardData): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const [r, g, b] = hexToRgb(data.school.primaryColor || "#16A34A");

  // Front card
  const x = 20, y = 25, w = 85, h = 54;
  doc.setFillColor(r, g, b);
  doc.roundedRect(x, y, w, h, 4, 4, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text((data.school.name || "School").toUpperCase(), x + 4, y + 6);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text(data.role.toUpperCase(), x + w - 4, y + 6, { align: "right" });
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(x + 4, y + 10, 22, 22, 2, 2, "F");
  doc.setTextColor(r, g, b);
  doc.setFontSize(7);
  doc.text("PHOTO", x + 15, y + 22, { align: "center" });
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(data.name, x + 28, y + 18);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(data.detail, x + 28, y + 23);
  doc.setFontSize(7);
  doc.text(`ID: ${data.code}`, x + 28, y + 28);
  // QR placeholder
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(x + w - 18, y + h - 18, 14, 14, 1, 1, "F");
  doc.setTextColor(r, g, b);
  doc.setFontSize(6);
  doc.text("QR", x + w - 11, y + h - 10, { align: "center" });

  // Back card
  const y2 = y + h + 8;
  doc.setDrawColor(r, g, b);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(x, y2, w, h, 4, 4, "FD");
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("Back of card", x + 4, y2 + 7);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(110, 110, 110);
  doc.text("EMERGENCY CONTACT", x + 4, y2 + 14);
  doc.setTextColor(20, 20, 20);
  doc.text(data.emergencyContact || "—", x + 4, y2 + 18);
  doc.setTextColor(110, 110, 110);
  doc.text("SCHOOL CONTACT", x + 4, y2 + 25);
  doc.setTextColor(20, 20, 20);
  doc.text(data.schoolContact || "—", x + 4, y2 + 29);
  doc.setTextColor(110, 110, 110);
  doc.text("SECURE TOKEN", x + 4, y2 + 36);
  doc.setFont("courier", "normal");
  doc.setFontSize(6);
  doc.setTextColor(20, 20, 20);
  doc.text(data.token, x + 4, y2 + 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6);
  doc.setTextColor(140, 140, 140);
  doc.text("If found, please return to the school. The QR is the only valid identifier.", x + 4, y2 + 48, { maxWidth: w - 8 });

  return doc;
}

export function downloadIdCard(data: IdCardData) {
  const doc = buildIdCardPdf(data);
  doc.save(`id-${data.code.toLowerCase()}.pdf`);
}

export function previewIdCard(data: IdCardData): string {
  return buildIdCardPdf(data).output("datauristring");
}

export function printIdCard(data: IdCardData) {
  const doc = buildIdCardPdf(data);
  const url = doc.output("bloburl");
  const w = window.open(url, "_blank");
  if (w) w.addEventListener("load", () => w.print());
}
